### PR TITLE
[feat-76] support drag and drop of mod files (zip/dll files only)

### LINKED ISSUE #76: [FEAT.] : Drag drop mod to install it
**Is your feature request related to a problem? Please describe.**
We can't manually install mod to a version.

**Describe the solution you'd like**
Drag and drop zip or dll of a mod onto the liste of mods to install it

**Describe alternatives you've considered**
No alternative

**Additional context**

drag drop mod

### PR DESCRIPTION
**Pull request by silentrald**
Closes #76
[Discord QOL](https://discord.com/channels/1049624409276694588/1274846674845433937)

## Notes

- When a file is dragged and dropped on the mods component, this will copy (if dll) or extract (if zip) the files to the `IPA/Pending` folder.
- Currently blocked by #649

## Screenshots

image

## Future features

- **External mods tracker** - so that users can view what external mods they have.
  - Warning prompt to ask the user if they want to overwrite an existing mod file/s
- **Disable mods support** - BSIPA support mod disabling, looked into `UserData/Disabled Mods.json`

### CODE REVIEW

**Comment by silentrald** [comment]
Hi @Zagrios, should be done with the PR. Only missing some art assets and resource text but most of the logic should be done. Can you check if I missed any handlings?

Also for the SonarCloud code analysis, can you also check if I need to resolve those or the code should be safe? Can't really check in my local development if I've resolve them quite right.

**Comment by Zagrios** [comment]
Hi I will try to review your PR this week 👌 hopefully tomorrow

**Comment by Zagrios** [comment]
@silentrald can you resolve conflicts ?

**Comment by silentrald** [comment]
@Zagrios rebased 👌

Although can we leave #76 since maybe **External mods tracker** is kinda crucial for that issue. Will do that in a separate PR once this gets merged, so that the changes are incremental and not in one go, like my previous change 😅

**Review by Zagrios — APPROVED** [review]
Seems good to me 🙌

**Comment by Zagrios** [comment]
Thanks @silentrald ❤️ 
Merging 🚀

**Pull request merged**
