### PR TITLE
[feat] defaultly open to the last version launched on startup

### PR DESCRIPTION
**Pull request by silentrald**
Feature request in [discord](https://discord.com/channels/1049624409276694588/1291894199683256320) regarding UX issues for new users.

### Additional Changes

* Changed labels "Select a version" to "Download a version" to not confuse new users if they are selecting their currently installed version.

### CODE REVIEW

**Comment by Zagrios** [comment]
@silentrald can you resolve conflicts ?

**Comment by silentrald** [comment]
@Zagrios rebased the PR👌. Everything should be fine.

**Review by Zagrios — APPROVED** [review]
Seems good to me 🙌 
Tested, it works great 👌

**Comment by Zagrios** [comment]
Thanks @silentrald ❤️ 
Merging 🚀

**Pull request merged**
