### PR TITLE
[bugfix] fix oculus launch by using sideloading

### PR DESCRIPTION
**Pull request by Zagrios**
image

### CODE REVIEW

**Comment by AltyFox** [comment]
@Zagrios please specify that this is a one-time permission, and won't be necessary in the future

**Comment by Zagrios** [comment]
> @Zagrios please specify that this is a one-time permission, to permanently unlock the feature.

yep done 😉

**Comment by AltyFox** [comment]
> > @Zagrios please specify that this is a one-time permission, to permanently unlock the feature.
> 
> yep done 😉

I like the wording, thank you!

**Comment by AltyFox** [comment]
@Zagrios to maintain consistency with the rest of our utilities, there should be a way to teach the user how to manually do this in case they don't want to provide administrator access for whatever reason

**Comment by Zagrios** [comment]
> @Zagrios to maintain consistency with the rest of our utilities, there should be a way to teach the user how to manually do this in case they don't want to provide administrator access for whatever reason

Yeah okay, I will add a button "I want to do it manually" or "How to do it manually" which will open a page on the BSM wiki 👌

**Pull request merged**
