### PR TITLE
[feat-706] show DepotDownloader missing executable error

### LINKED ISSUE #706: [BUG] : Steam login closes itself, then can't login or try to download a version
### Issue encountered

- Try to download a Steam version;
- Asks me to log into Steam;
- Get partway through login;
- Login box closes randomly;
- Try to click "download" again, get notification in top right saying something went wrong.

I've managed to log in by scanning the QR code on my phone, but only if I'm very quick!

### Expected Behavior

_No response_

### Steps to Reproduce

_No response_

### Operating System

None

### Version

1.4.14

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by silentrald**
Closes #706

image

## How to Test

* Rename either `DepotDownloader` or `DepotDownloader.exe` to a different name, and try to download a new Beat Saber version.
* Revert the names back once done testing.

### CODE REVIEW

**Comment by silentrald** [comment]
@Zagrios, please check if the following texts are fine before I do translation. Thanks thanks

**ExeNotFoundWindows:** "DepotDownloader.exe" is missing. Please check if the executable is quarantined by your anti-virus.
**ExeNotFoundLinux:** "DepotDownloader" binary is missing.

**Comment by Zagrios** [comment]
> @Zagrios, please check if the following texts are fine before I do translation. Thanks thanks
> 
> **ExeNotFoundWindows:** "DepotDownloader.exe" is missing. Please check if the executable is quarantined by your anti-virus. **ExeNotFoundLinux:** "DepotDownloader" binary is missing.

@silentrald  That's sounds good to me 👌

**Comment by silentrald** [comment]
@Zagrios PR is ready to merge. Just change the term "binary" to "executable" since its more fitting with the file being an executable for Linux.

**Review by Zagrios — APPROVED** [review]
All good to me 🙌

**Comment by Zagrios** [comment]
Thanks @silentrald ❤️ 
Merging 🚀

**Pull request merged**
