### PR TITLE
[feat] add proton logs in advance launch settings for linux

### PR DESCRIPTION
**Pull request by silentrald**
Added a way write the proton logs within the BS version "Logs" folder.

As of https://github.com/Zagrios/bs-manager/pull/708/commits/6b5ccfe08b3b74819401e03d88e4dd6a7bfe4c10
image

image

**Texts**
proton-logs: Proton Logs
proton-logs-description: Enables the recording of proton logs for this Beat Saber install to "{versionPath}".

### CODE REVIEW

**Comment by Zagrios** [comment]
@silentrald i've just implemented a rework for the advanced launch options

**Comment by silentrald** [comment]
@Zagrios reworked the PR to the change. Also fixed some issues with the previous PR.

* `es.json` had incorrect key heirarchy for skipstream and map-editor.
* `jp.json` missing map-editor translation.
* Fixed an issue with `useTranslateV2.text` where normal text containing "[]" throws an error.
* Added `break-words` for Tippy text where a single long word could overflow the container.

**Review by Zagrios — APPROVED** [review]
Seems good to me 🙌

**Comment by Zagrios** [comment]
Thanks @silentrald 🙌 
Merging 🚀

**Pull request merged**
